version: '3.8'

services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - app-network
  
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootcayo
      MYSQL_DATABASE: venta
      MYSQL_USER: cayo
      MYSQL_PASSWORD: 1234

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootcayo
      UPLOAD_LIMIT: 100M

    depends_on:

      - db

    networks:

      - app-network


volumes:

  db_data:


networks:

  app-network:

    driver: bridge